### ISSUE TITLE
Add document to a patient profile

### ISSUE THREAD

**Issue by shilpikhemka11** [uzumakit/medDNAAppFE#27]

**Comment by ganeshpujari** [comment]
Needs 2 API:-
1.>URL:-https://dev.meddna.in:8000/doc/upload
METHOD:-POST
DATA:-
NOTE:--Contact to Abhishek sir for more info abt Upload


2.>ttps://dev.meddna.in:8000/doc/api/Doctor/sharedResource/
METHOD:-POST
DATA:-

{"path":"/media/patientresources/146122151667-spt.html","name":"spt.html","type":"html","patId":72}
