### ISSUE TITLE
Reschedule/ Cancel/ Confirm appointment

### ISSUE THREAD

**Issue by shilpikhemka11** [uzumakit/medDNAAppFE#32]

**Comment by ganeshpujari** [comment]
for Cancel:-----
URL:-https://dev.meddna.in:8000/doc/api/Appointment/status/
METHOD:-PUT
DATA:-
{"status":"cancel","aptId":156}

for Confirm:----
URL:-https://dev.meddna.in:8000/doc/api/Appointment/status/
METHOD:-PUT
DATA:-
{"status":"cancel","aptId":156}


for Reschedule:--
URL:-https://dev.meddna.in:8000/doc/api/Appointment/appointment/
METHOD:-PUT
DATA:-
{"type":"revisit","charges":200,"reason":"","aptId":156,"status":"confirm","date":"04-21-2016","time":"15:00","doctorHealthCentreId":1049,"patient":{"id":54,"firstName":"Suraj","email":"khandale.lenendra@gmail.com","lastName":"Khandale","relation":"ACCOUNT_MANAGER","dateOfBirth":"2016-3-3 06:00:00+0530","user":{"id":43,"username":"7040772649","email":"khandale.lenendra@gmail.com","group":"patient","first_name":"Suraj","last_name":"Khandale"},"mobileNumber":"7040772649","gender":"None","addressLine1":"Magarpatta City","addressLine2":"","city":"Pune","state":"Maharashtra","country":"India","zipCode":411013,"category":"General","weight":"0","bloodGroup":null,"label":"Suraj Khandale 7040772649","height":"0","bloodPressure":"0"}}
