### ISSUE TITLE
Add Prescription

### ISSUE THREAD

**Issue by shilpikhemka11** [uzumakit/medDNAAppFE#35]

**Comment by ganeshpujari** [comment]
URL:-http://localhost:8000/doc/api/Doctor/prescription/
METHOD:-POST
DATA:-
{"referToDoctor":"","advice":"","addToFavTreatment":true,"addToFavMed":true,"addToFavTest":true,"doctorHealthCentreId":241,"docId":216,"patId":1,"description":"test desc","revisit":false,"revisitDate":"","unit":"days","notify":false,"notificationType":"SMS,EMAIL","attachment":"","date":"4-21-2016","bloodPressure":"0","weight":"0","height":"0","bloodGroup":"O+","email":"nitinbhosalepatil55@gmail.com","shareWithPatient":true,"category":"General","dateOfBirth":"2016-4-4 06:00:00+0530","address":{"addressLine1":"Dhole Patil Road, Sangamvadi, ","addressLine2":"002","city":"Pune","state":"Maharashtra","zipCode":"411001","country":"India","email":"nitinbhosalepatil55@gmail.com"},"medicines":[{"name":"nice","company":"cipla","dosage":"1-0-1-TAB-AF-","duration":"10 days"}],"investigations":[{"name":"t1","description":""},{"name":"t2","description":""}],"treatments":[{"name":"treat1","cost":"200","discount":"10","sittings":1}]}
